### ISSUE TITLE
Deprecated `scrollbar_thumb.background` usage

### ISSUE THREAD

**Issue by maxdeviant** [Takk8IS/call-trans-opt-received-2-19-98-13-24-18-rec-log-theme-for-zed#5]
This extension has been identified as using the deprecated `scrollbar_thumb.background` style property.

This property has been deprecated in favor of `scrollbar.thumb.background`. Please migrate to using the new property.

The following themes are impacted:

- Theme "Call trans opt: received. 2-19-98 13:24:18 REC:Log>" is using deprecated style property `scrollbar_thumb.background`

**Comment by davccavalcante** [comment]
> This extension has been identified as using the deprecated `scrollbar_thumb.background` style property.
> 
> This property has been deprecated in favor of `scrollbar.thumb.background`. Please migrate to using the new property.
> 
> The following themes are impacted:
> 
> * Theme "Call trans opt: received. 2-19-98 13:24:18 REC:Log>" is using deprecated style property `scrollbar_thumb.background`

Done

**Comment by seantiz** [comment]
> > This extension has been identified as using the deprecated `scrollbar_thumb.background` style property.
> > This property has been deprecated in favor of `scrollbar.thumb.background`. Please migrate to using the new property.
> > The following themes are impacted:
> > 
> > * Theme "Call trans opt: received. 2-19-98 13:24:18 REC:Log>" is using deprecated style property `scrollbar_thumb.background`
> 
> Done

I'm still getting this warning flagged by Zed, but I'm on v0.1.1 still and I think you pushed this to v0.1.2. The latest version does not show in the Zed Extensions listings.
